name: electronics_store
description: GraduationProject.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: 2.3.2
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  local_auth: ^2.1.7
  go_router: ^12.1.1
  intl: ^0.18.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  google_fonts: ^6.1.0
  firebase_core: ^3.13.0
  fl_chart: ^0.55.2  # Downgraded to a more compatible version
  path_provider: ^2.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10


flutter:
  uses-material-design: true

fonts:
  - family: Cairo
